version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
    volumes:
      - './database:/docker-entrypoint-initdb.d/'
  go-api:
    build: ./backend
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - './backend:/build'
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
